### ISSUE TITLE
Many network tests failing on AIX in JDK20 (with UnknownHostException: Hostname and service name not provided)

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3178]
sun/security/krb5/auto/NoAddresses.java appears to fail across all available AIX machines:

```
java.net.UnknownHostException: adopt06: adopt06: Hostname and service name not provided or found
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1791)
	at NoAddresses.main(NoAddresses.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.net.UnknownHostException: adopt06: Hostname and service name not provided or found
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
	at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1061)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1683)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1004)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1673)
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1786)
	... 5 more

JavaTest Message: Test threw exception: java.net.UnknownHostException: adopt06: adopt06: Hostname and service name not provided or found
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.net.UnknownHostException: adopt06: adopt06: Hostname and service name not provided or found
    
```

**Test Info**
Test Name: jdk_security4_1
Test Duration: 13 min 8 sec
Machine: test-osuosl-aix72-ppc64-6
TRSS link for the test output: https://trss.adoptium.net/output/test?id=64b3f9a817052c671580a5fe

**Build Info**
Build Name: Test_openjdk20_hs_sanity.openjdk_ppc64_aix
Jenkins Build start time: Jul 15 2023, 09:08 pm
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk20_hs_sanity.openjdk_ppc64_aix/110/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=64b3f8a617052c671580a04d

**Java Version**
openjdk version "20.0.1-beta" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9-202307152344 (build 20.0.1-beta+9-202307152344)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9-202307152344 (build 20.0.1-beta+9-202307152344, mixed mode)

**This test has been failed 17 times since Jun 10 2023, 08:34 pm**
**Java Version when the issue first seen**
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9 (build 20.0.1+9)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9 (build 20.0.1+9, mixed mode)
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk20_hs_sanity.openjdk_ppc64_aix/94/

The test failed on machine test-osuosl-aix72-ppc64-6 2 times 
The test failed on machine test-osuosl-aix72-ppc64-3 3 times 
The test failed on machine test-osuosl-aix72-ppc64-5 4 times 
The test failed on machine test-osuosl-aix72-ppc64-4 2 times 
The test failed on machine test-osuosl-aix72-ppc64-1 1 times 
The test failed on machine test-osuosl-aix72-ppc64-2 4 times 
The test failed on machine build-osuosl-aix72-ppc64-2 1 times 

[Rerun in Grinder](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_security4_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=20&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-aix-ppc64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=sw.os.aix.7_2&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=41&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

-----

Other network related targets also failing on AIX with same issue, examples:
[jdk_nio](https://trss.adoptium.net/output/test?id=64b3fa9a17052c671580ae05) from https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_ppc64_aix_testList_2/6/

**Comment by smlambert** [comment]
Related: https://github.com/adoptium/infrastructure/issues/3030

**Comment by aixtools** [comment]
All hosts - or some? As most systems are a clone of `adopt10`.

I can look for differences - but a known working server compared with a known failing server works is the preferred starting point.

**Comment by smlambert** [comment]
I believe the issue is observed on test-osuosl-aix72-ppc64-4, test-osuosl-aix72-ppc64-5, test-osuosl-aix72-ppc64-6.  

Though I have exhaustively looked at all hosts, anecdotally -1, -2, -3 look like they do not have this issue.

**Comment by smlambert** [comment]
To reproduce this issue,  use this Rerun in Grinder [link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=jdk_security4_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=20&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=sw.os.aix.7_2&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) and set LABEL to be the hostname to run on, for example set LABEL to test-osuosl-aix72-ppc64-6.

**Comment by adamfarley** [comment]
It looks like -3 and -4 were [removed from the ansible inventory file back in May](https://github.com/adoptium/infrastructure/pull/3053), so perhaps these machines can be ignored if they are pending deletion. 

I mention the pending deletion of these machines [here](https://github.com/adoptium/infrastructure/issues/3179).

**Comment by aixtools** [comment]
Here are the current records:

```
BUILD:
      - osuosl:
          aix72-ppc64-1: {ip: 140.211.9.166, description: p8-java1-adopt10.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-2: {ip: 140.211.9.12, description: p8-aix1-adopt02.osuosl.org, 7200-02-04-1914}
```

```
TEST:
      - osuosl:
          aix72-ppc64-1: {ip: 140.211.9.28, description: p8-aix1-adopt03.osuosl.org, 7200-04-02-2028}
          aix72-ppc64-2: {ip: 140.211.9.36, description: p8-aix1-adopt04.osuosl.org, 7200-02-05-1938}
          aix72-ppc64-3: {ip: 140.211.9.168, description: p8-java1-adopt07.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-4: {ip: 140.211.9.169, description: p8-java1-adopt08.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-5: {ip: 140.211.9.99, description: p9-aix1-adopt05.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-6: {ip: 140.211.9.100, description: p9-aix1-adopt06.osuosl.org, 7200-02-04-1914}
          aix73-ppc64-1: {ip: 140.211.9.10, description: p8-aix1-adopt01.osuosl.org, 7300-01-02-2320}
```

All systems are build and active.
-1 and -2 were built long ago (before the new build-aix72-1), the systems -[3,4,5,6} are all cloned from the build-aix72-1 system, the aix73 was built from DVD.

After the cloning the playbook, afaik, was rerun over all the all the aix72 systems - and obviously, the aix73 system was built/configured using the playbook.

Any differences are because someone has made changes manually.

No control and/or change history on manual changes.
