### ISSUE TITLE
Improve search of Python3 in DNF role in Aix playbook

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3325]
ref https://github.com/adoptium/infrastructure/issues/3274#issuecomment-1877442593

In the dnf role in the AIX playbook, ansible should look for python3 in more than just /opt/freeware/bin

https://github.com/adoptium/infrastructure/blob/0077e292c4691e2f477f361d6535382dda938363/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/dnf/tasks/main.yml#L9

```
- name: Fail if python3 is not available
  stat:
    path: /opt/freeware/bin/python3
  register: python3_installed
  failed_when: not python3_installed.stat.exists
```
