### ISSUE TITLE
System unavailable: Wazuh - SIEM System

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3728]
- Please put the system name in the title of this issue.

Wazuh / Web Dashboard / Indexer Issue

- Please describe the issue:

The Wazuh system has stopped showing alerts. This needs to be investigated and resolved.

Tasks:
- [X] - Investigate and resolve initial problem - Indexer out of shards
- [X] - Identify root cause - Hit 1000 shard limit.
- [x] - Implement solution - enable auto housekeeping, initial limit of 9 months data
- [x] - Add missing data back into Wazuh indexes.

**Comment by steelhead31** [comment]
Indexer had run out of shards, have removed data from Oct, Nov, Dec 2023, so "only" have 9 months of data. Have noticed data for the last month has not been indexed correctly. Log files are still available on the Wazuh server, so will investigate re-indexing and adding this data. Real time alerts and monitoring are now in place.

**Comment by steelhead31** [comment]
Re ingesting log files in progress... details on how to achieve this are contained in this handy blog post, it'll likely take the weekend to complete.. https://wazuh.com/blog/recover-your-data-using-wazuh-alert-backups/

**Comment by steelhead31** [comment]
For future reference:

https://wazuh.com/blog/wazuh-index-management/

Get the python script from this blog post

  
https://wazuh.com/blog/recover-your-data-using-wazuh-alert-backups/

```
vi /usr/share/filebeat/module/wazuh/alerts/manifest.yml
```

Change This

```
module_version: 0.1
var:
 - name: paths
   default:
     - /var/ossec/logs/alerts/alerts.json
 - name: index_prefix
   default: wazuh-alerts-4.x-
input: config/alerts.yml
ingest_pipeline: ingest/pipeline.json
```

To This

```
module_version: 0.1
var:
 - name: paths
   default:
     - /var/ossec/logs/alerts/alerts.json
     - /tmp/recovery.json
 - name: index_prefix
   default: wazuh-alerts-4.x-
input: config/alerts.yml
ingest_pipeline: ingest/pipeline.json
```

  
Then restart filebeat ( and check its running... )

```
# systemctl restart filebeat
# filebeat test output
elasticsearch: https://127.0.0.1:9200...
 parse url... OK
 connection...
   parse host... OK
   dns lookup... OK
   addresses: 127.0.0.1
   dial up... OK
 TLS...
   security: server's certificate chain verification is enabled
   handshake... OK
   TLS version: TLSv1.2
   dial up... OK
 talk to server... OK
 version: 7.10.2
```

Run The Restore Script

```
nohup ./recovery.py -eps 500 -min 2024-08-06T00:00:00 -max 2024-09-05T23:59:59 -o /tmp/recovery.json -log ./recovery.log -sz 2.5 &
```

Monitor progress using this..

```
cut -b 16-25 /tmp/recovery.json |sort |uniq -c
```
