### ISSUE TITLE
2 new AIX73 build machines

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3920]
2 P10 lpars have been created by the IBM team

p10-aix-adopt03.osuosl.org 140.211.9.21
p10-aix-adopt04.osuosl.org 140.211.9.66

I have set up the machines using the ansible playbooks. However there are still some bits left to do.

https://github.com/adoptium/infrastructure/blob/4a5620117cd586b8194f0c050e754a500fc7c98c/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/dnf/tasks/main.yml#L126
```
    - name: Install cmake 3.14.3 (See https://github.com/AdoptOpenJDK/openjdk-build/issues/2492)
      dnf:
        name: cmake-3.14.3
        state: present
        update_cache: yes
        disable_excludes: all
      tags:
        - rpm_install
        - cmake
```
I wasnt able to install Cmake using this task. 
```
root@p10-aix-adopt03:[/root]dnf install cmake-3.14.3
Last metadata expiration check: 4:21:41 ago on Fri Apr  4 12:34:39 2025.
No match for argument: cmake-3.14.3
Error: Unable to find a match: cmake-3.14.3
```

Both the v13 and 16 XL compilers installed fine, but give an error log which suggests they are not supported on AIX7.3

```
root@p10-aix-adopt03:[/root]/opt/IBM/xlC/13.1.3/bin/xlc -qversion
/opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-287 (S) This compiler does not support AIX 7.3. Please check with IBM (http://www-01.ibm.com/support/docview.wss?rs=43&uid=swg21326972) to see if there is a PTF for this compiler that supports this AIX level.

root@p10-aix-adopt03:[/root]/opt/IBM/xlC/16.1.0/bin/xlc -qversion
/opt/IBM/xlC/16.1.0/bin/.orig/xlc: 1501-287 (S) This compiler does not support AIX 7.3. Please check with IBM (http://www-01.ibm.com/support/docview.wss?rs=43&uid=swg21326972) to see if there is a PTF for this compiler that supports this AIX level.
```

Had a bit of an error with the [rbac](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/rbac/tasks/main.yml) role

```
- name: Create auth ojdk.rtclk
  when: rtclk_exists.rc == 2
  shell:
    mkrole authorizations='ojdk.rtclk,ojdk.proccore' dfltmsg='Adoptium Role for testing' ojdk.rtclk
  register: _rtclk
  failed_when: _rtclk.rc != 0 and _rtclk.rc != 17
  tags: rbac

- name: Create auth ojdk.proccore
  when: rtcore_exists.rc == 2
  shell:
    mkauth dfltmsg="PV_PROC_CORE for to allow process core dumps" ojdk.proccore
  register: _rtcore
  failed_when: _rtcore.rc != 0 and _rtcore.rc != 17
  tags: rbac
```
These tasks did not work. In fact the command from the second task, `mkauth dfltmsg="PV_PROC_CORE for to allow process core dumps" ojdk.proccore` needed to be run before the first. And in the command in the first task, `mkrole authorizations='ojdk.rtclk,ojdk.proccore' dfltmsg='Adoptium Role for testing' ojdk.rtclk`, I needed to remove `ojdk.rtclk` from `authorizations` for the command to work
